- name: initialize all servers
  hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - initialize-server

#hosts: jenkins-master
  # remote_user: provision
  # become: yes
  # roles:
    - geerlingguy.jenkins

# hosts: databases
  # 
  # roles:

